name: SiteWatchdog
on: 
  push:
    branches:
      - main
  schedule:
    - cron:  '*/25 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Run SiteWatchDog
        uses: QJoly/SiteWatchdog@v0.1.1
        env:
          SITES_YAML_PATH: .github/sites.yaml
          README_TEMPLATE_PATH: .github/README.md.tmpl

      - name: Push changes if needed
        run: |
          git add README.md
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config user.name "GitHub Actions[Bot]"
          # Push only if README.md has been modified
          if [[ $(git status --porcelain "README.md" | wc -l) -gt 0 ]]; then git commit -m "[BOT] Update README.md"; git push; fi